### ISSUE TITLE
Add documentation on how to manually migrate keys in CLI

### ISSUE THREAD

**Issue by lacabra** [scrtlabs/SupernovaDocs#1]
Hi @reuvenpo ;)

In the [CLI Changes](https://github.com/scrtlabs/SupernovaDocs/blob/master/app%20developers/cli.md) document there is the following mention:

> Key format has been changed, and keys must be manually migrated to be used in the new CLI

It would be good to include documentation on how to go about it. Migrating keys is a stressful step because of the high-stakes implications of doing it wrong and losing access to your own account. I anticipate many will request additional details on how to do it.

**Comment by Cashmaney** [comment]
You'll never lose access to your own account, fear not. We'll add the specific commands, but since it's just standard export/import from the CLI there's no danger here.

In the meantime you can refer to here: https://github.com/scrtlabs/SupernovaDocs/blob/master/validators/migrate-a-validator.md#2-confirm-you-have-the-recovery-seed-phrase-information-for-the-active-key-running-on-the-old-machine

**Comment by reuvenpo** [comment]
@lacabra Please check out this new section added to the CLI Changes document :)
https://github.com/scrtlabs/SupernovaDocs/blob/master/app%20developers/cli.md#migrating-keys

Let us know if you think it's clear for users 🙂

**Comment by lacabra** [comment]
Thanks @Cashmaney and @reuvenpo for your prompt replies. @reuvenpo additions addressed my concerns, hence I'm closing this issue. Thanks again! 🙏
